# Generated by Django 2.0 on 2017-12-14 14:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=10)),
                ('total_count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('ordered_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Orders detail',
            },
        ),
        migrations.CreateModel(
            name='Shop_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'All shop item',
            },
        ),
        migrations.CreateModel(
            name='UsersAndOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('order_date', models.DateTimeField()),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('total_sum', models.IntegerField()),
            ],
            options={
                'verbose_name': 'User Order',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.UsersAndOrders'),
        ),
    ]
