# Generated by Django 2.0 on 2017-12-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_item',
            name='features',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
