# Generated by Django 2.0 on 2017-12-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_shop_item_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_item',
            name='features',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
