# Generated by Django 2.0 on 2017-12-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20171215_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_item',
            name='image_add1',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop_item',
            name='image_add2',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop_item',
            name='image_add3',
            field=models.ImageField(default='aaa', upload_to=''),
            preserve_default=False,
        ),
    ]
