# Generated by Django 2.0 on 2017-12-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20171220_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopsettings',
            name='footer',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='items_per_page',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='shop_name',
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
