# Generated by Django 2.0 on 2017-12-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_auto_20171220_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='footer',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='shop_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
